<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="78725" started-at="2016-06-13T09:07:49Z" finished-at="2016-06-13T09:09:08Z">
    <groups>
    </groups>
    <test name="Regression Test Suite" duration-ms="78725" started-at="2016-06-13T09:07:49Z" finished-at="2016-06-13T09:09:08Z">
      <class name="com.cybage.alm.test.TestSuite2">
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="10255" started-at="2016-06-13T14:37:50Z" data-provider="loginData" finished-at="2016-06-13T14:38:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@a776e]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="9457" started-at="2016-06-13T14:38:00Z" data-provider="loginData" finished-at="2016-06-13T14:38:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@79145d5a]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="9476" started-at="2016-06-13T14:38:09Z" data-provider="loginData" finished-at="2016-06-13T14:38:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@338494fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="8841" started-at="2016-06-13T14:38:19Z" data-provider="loginData" finished-at="2016-06-13T14:38:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@505a9d7c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="9711" started-at="2016-06-13T14:38:28Z" data-provider="loginData" finished-at="2016-06-13T14:38:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@758c83d8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="9528" started-at="2016-06-13T14:38:37Z" data-provider="loginData" finished-at="2016-06-13T14:38:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@129b4fe2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="9580" started-at="2016-06-13T14:38:47Z" data-provider="loginData" finished-at="2016-06-13T14:38:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@5af3a0f]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="loginTest" duration-ms="11527" started-at="2016-06-13T14:38:57Z" data-provider="loginData" finished-at="2016-06-13T14:39:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@4c4d27c8]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="teadDown()[pri:0, instance:com.cybage.alm.test.TestSuite2@1534f01b]" name="teadDown" is-config="true" duration-ms="0" started-at="2016-06-13T14:39:08Z" finished-at="2016-06-13T14:39:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
      </class> <!-- com.cybage.alm.test.TestSuite2 -->
    </test> <!-- Regression Test Suite -->
  </suite> <!-- Suite1 -->
</testng-results>
