<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="12" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="125651" started-at="2016-06-14T13:02:12Z" finished-at="2016-06-14T13:04:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="125651" started-at="2016-06-14T13:02:12Z" finished-at="2016-06-14T13:04:17Z">
      <class name="com.cybage.alm.test.TestSuite2">
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="10948" started-at="2016-06-14T18:32:12Z" data-provider="loginData" finished-at="2016-06-14T18:32:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@45d84a20]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9451" started-at="2016-06-14T18:32:23Z" data-provider="loginData" finished-at="2016-06-14T18:32:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@53dacd14]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9271" started-at="2016-06-14T18:32:33Z" data-provider="loginData" finished-at="2016-06-14T18:32:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@43aaf813]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9101" started-at="2016-06-14T18:32:42Z" data-provider="loginData" finished-at="2016-06-14T18:32:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@246f8b8b]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9101" started-at="2016-06-14T18:32:51Z" data-provider="loginData" finished-at="2016-06-14T18:33:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@66b7550d]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9217" started-at="2016-06-14T18:33:00Z" data-provider="loginData" finished-at="2016-06-14T18:33:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@20f12539]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9491" started-at="2016-06-14T18:33:09Z" data-provider="loginData" finished-at="2016-06-14T18:33:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@3fa2213]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-ON] but found [SIGN-OFF]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-ON] but found [SIGN-OFF]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:18)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="10032" started-at="2016-06-14T18:33:19Z" data-provider="loginData" finished-at="2016-06-14T18:33:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@3f792b9b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="registerTest" duration-ms="12325" started-at="2016-06-14T18:33:29Z" data-provider="registerData" finished-at="2016-06-14T18:33:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@25e2a451]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="registerTest" duration-ms="12009" started-at="2016-06-14T18:33:41Z" data-provider="registerData" finished-at="2016-06-14T18:33:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@662f5666]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="registerTest" duration-ms="13617" started-at="2016-06-14T18:33:53Z" data-provider="registerData" finished-at="2016-06-14T18:34:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@55b5f5d2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="registerTest(com.cybage.alm.data.RegisterData)[pri:2, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="registerTest" duration-ms="10676" started-at="2016-06-14T18:34:07Z" data-provider="registerData" finished-at="2016-06-14T18:34:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.RegisterData@14f5da2c]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerTest -->
        <test-method status="PASS" signature="teadDown()[pri:0, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="teadDown" is-config="true" duration-ms="0" started-at="2016-06-14T18:34:18Z" finished-at="2016-06-14T18:34:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
      </class> <!-- com.cybage.alm.test.TestSuite2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
