<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="77696" started-at="2016-06-13T10:44:08Z" finished-at="2016-06-13T10:45:25Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="77696" started-at="2016-06-13T10:44:08Z" finished-at="2016-06-13T10:45:25Z">
      <class name="com.cybage.alm.test.TestSuite2">
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="10185" started-at="2016-06-13T16:14:08Z" data-provider="loginData" finished-at="2016-06-13T16:14:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@45d84a20]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="10289" started-at="2016-06-13T16:14:18Z" data-provider="loginData" finished-at="2016-06-13T16:14:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@62f68dff]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="8845" started-at="2016-06-13T16:14:29Z" data-provider="loginData" finished-at="2016-06-13T16:14:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@5b1f29fa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9552" started-at="2016-06-13T16:14:37Z" data-provider="loginData" finished-at="2016-06-13T16:14:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@1c6804cd]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9831" started-at="2016-06-13T16:14:47Z" data-provider="loginData" finished-at="2016-06-13T16:14:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@45e37a7e]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9641" started-at="2016-06-13T16:14:57Z" data-provider="loginData" finished-at="2016-06-13T16:15:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@665df3c6]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9051" started-at="2016-06-13T16:15:07Z" data-provider="loginData" finished-at="2016-06-13T16:15:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@607fbe09]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="loginTest(com.cybage.alm.data.LoginData)[pri:1, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="loginTest" duration-ms="9935" started-at="2016-06-13T16:15:16Z" data-provider="loginData" finished-at="2016-06-13T16:15:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[com.cybage.alm.data.LoginData@565b064f]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [SIGN-OFF] but found [SIGN-ON]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [SIGN-OFF] but found [SIGN-ON]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.cybage.alm.pages.LoginPage.signin(LoginPage.java:20)
	at com.cybage.alm.test.TestSuite2.loginTest(TestSuite2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="teadDown()[pri:0, instance:com.cybage.alm.test.TestSuite2@51e5fc98]" name="teadDown" is-config="true" duration-ms="4" started-at="2016-06-13T16:15:26Z" finished-at="2016-06-13T16:15:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
      </class> <!-- com.cybage.alm.test.TestSuite2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
